# Generated by Django 3.1.5 on 2021-01-14 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210114_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 16, 49, 55, 917894)),
        ),
    ]
